---
title: "Discussion plots"
author: "Sam Siljee"
date: "2026-06-22"
output: html_document
---
 Script to make the plots for the discussion chapter.
 
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# Packages
library(dplyr) # Data manipulation
library(ggplot2) # Plotting
library(ggpubr) # Display equation on correlation of proteomics datasets
library(ggVennDiagram) # Make Venn diagrams

# Files and directories
input_dir <- paste0(getwd(), "/data/")
output_dir <- paste0(getwd(), "/../produced_plots/Misc/")

# Values
plot_width <- 8
plot_height <- 5.5
log_2_FC_cutoff <- log2(1.3)
adj_p_value_cutoff <- 0.05

# Files to load
LFQ_data <- paste0(output_dir, "../MS_results/LFQ/differential_abundances_LFQ.csv")
TMT_data <- paste0(output_dir, "../MS_results/TMT/differential_abundances_TMT.csv")
```

## Load the data
Loading the ouput of the multi-DDM analysis run in MATLAB. Results from the .mat object exported as .csv files.
```{r Load the data}
# Load custom functions and colours
source(paste0(input_dir, "../../Functions.R"))

# Read in MS results - merging LFQ and TMT results
prot_results <- merge(
  dplyr::select(
    mutate(
      read.csv(LFQ_data),
      LFQ_FC = log2FC,
      LFQ_pval = adj.pvalue
    ),
    Protein, LFQ_FC, LFQ_pval
  ),
  dplyr::select(
    mutate(
      read.csv(TMT_data),
      TMT_FC = log2FC,
      TMT_pval = adj.pvalue
    ),
    Protein, TMT_FC, TMT_pval
  ),
  all = TRUE
) %>%
  group_by(Protein) %>%
  summarise(
    LFQ_FC = mean(LFQ_FC, na.rm = TRUE),
    LFQ_pval = mean(LFQ_pval, na.rm = TRUE),
    TMT_FC = mean(TMT_FC, na.rm = TRUE),
    TMT_pval = mean(TMT_pval, na.rm = TRUE),
  )
```

## Quant numbers and venn diagram
```{r}
print(paste("Quantified in LFQ:", sum(!is.na(prot_results$LFQ_FC))))
print(paste("Quantified in TMT:", sum(!is.na(prot_results$TMT_FC))))
print(paste("Quantified in both:", sum(!is.na(prot_results$LFQ_FC) & !is.na(prot_results$TMT_FC))))
print(paste("Sig LFQ:", mean(prot_results$LFQ_pval < adj_p_value_cutoff, na.rm = TRUE)))
print(paste("Sig TMT:", mean(prot_results$TMT_pval < adj_p_value_cutoff, na.rm = TRUE)))

# Venn diagra off dataset overlap
# Filter data and make a list of unique proteins in each replicate
venn_list <- list(
  LFQ = prot_results$Protein[!is.na(prot_results$LFQ_FC)],
  TMT = prot_results$Protein[!is.na(prot_results$TMT_FC)]
)

# make the plot
ggVennDiagram(venn_list) +
  theme_void() +
  labs(
    title = paste0("LFQ and TMT dataset overlap")
  ) +
  ggplot2::scale_fill_gradient(low = "white", high = "red")

# Save the plot
ggsave(paste0(output_dir, "Dataset overlap venn diagram.png"), width = plot_width, height = plot_height)
```

## Correlate proteomics datasets
Correlate the fold-changes
```{r}
# Correlation of all proteins
prot_results %>%
  filter(is.finite(LFQ_FC)) %>%
  filter(!is.na(TMT_FC)) %>%
  ggplot(aes(x = LFQ_FC, y = TMT_FC)) +
  geom_point() +
  geom_smooth(method = "lm") +
  stat_cor(aes(label = after_stat(rr.label)), label.x = 1, label.y = 1.5) +
  stat_regline_equation(label.x = 1, label.y = 1.3) +
  theme_bw() +
  labs(
    x = "LFQ log2 fold change",
    y = "TMT log2 fold change",
    title = "Proteomics fold change correlation"
  ) +
  theme_bw()

# Save the plot
ggsave(paste0(output_dir, "Dataset correlation.png"), width = plot_width, height = plot_height)

# Correlation of significant proteins
prot_results %>%
  filter(is.finite(LFQ_FC)) %>%
  filter(TMT_pval < 0.05 & LFQ_pval < 0.05) %>%
  ggplot(aes(x = LFQ_FC, y = TMT_FC)) +
  geom_point() +
  geom_smooth(method = "lm") +
  stat_cor(aes(label = after_stat(rr.label)), label.x = 1, label.y = 1.5) +
  stat_regline_equation(label.x = 1, label.y = 1.3) +
  theme_bw() +
  labs(
    x = "LFQ log2 fold change",
    y = "TMT log2 fold change",
    title = "Proteomics significant fold change correlation"
  ) +
  theme_bw()

# Save the plot
ggsave(paste0(output_dir, "Significant dataset correlation.png"), width = plot_width, height = plot_height)
```
